language: java
jdk: openjdk8
services:
  - xvfb
    
before_install:
  - sudo apt-get install -y openjfx

install: skip

script:
  - ./mvnw package -DskipTests=true
    
cache:
  directories:
    - $HOME/.m2
